version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: fraud-api
    environment:
      - DATABASE_URL=postgresql+psycopg2://fraud:fraud@db:5432/fraud_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ../models_store:/app/models_store

  dashboard:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dashboard
    container_name: fraud-dashboard
    environment:
      - DASHBOARD_API_BASE_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api

  db:
    image: postgres:16
    container_name: fraud-db
    environment:
      POSTGRES_USER: fraud
      POSTGRES_PASSWORD: fraud
      POSTGRES_DB: fraud_db
    ports:
      - "5432:5432"
    volumes:
      - fraud_pgdata:/var/lib/postgresql/data

volumes:
  fraud_pgdata:
