version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: fraud-api
    environment:
      - DATABASE_URL=postgresql+psycopg2://fraud:fraud@db:5432/fraud_db
      - API_HOST=0.0.0.0
      - API_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ../models_store:/app/models_store

  db:
    image: postgres:16
    container_name: fraud-db
    environment:
      POSTGRES_USER: fraud
      POSTGRES_PASSWORD: fraud
      POSTGRES_DB: fraud_db
    ports:
      - "5432:5432"
    volumes:
      - fraud_pgdata:/var/lib/postgresql/data

volumes:
  fraud_pgdata:
